import { ChakraProvider } from "@chakra-ui/react"
import Navbar from "../components/Navbar"
import Footer from "../components/footer1.tsx/page"
// adjust import paths
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* Bootstrap CSS */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
        />
        {/* Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <ChakraProvider>
        <Navbar />
        {children}
<Footer/>
        </ChakraProvider>
        </body>
    </html>
  )
}
